"""Format checker. Works for ANY agent built on this template. No LLM needed.

Run:  python -m pytest tests/test_tool_format.py
Every failure message says what to fix. Do not edit this file.
"""
import inspect
import json
import re
from pathlib import Path

import pytest

from src.tools import TOOL_FUNCTIONS, TOOL_SCHEMAS

SPEC_PATH = Path(__file__).resolve().parent.parent / "docs" / "03_tool_spec.md"
GIVEN_TOOLS = {"calculate"}  # already implemented, does not count as a new tool
MIN_NEW_TOOLS = 4
JUNK = {"string": "__no_such_thing__", "integer": -1, "number": -1.0, "boolean": False, "array": [], "object": {}}

tool = pytest.mark.parametrize("name", sorted(TOOL_FUNCTIONS))


def _schema(name: str) -> dict:
    """Return the "function" part of the schema registered under this tool name."""
    for schema in TOOL_SCHEMAS:
        if isinstance(schema, dict) and schema.get("function", {}).get("name") == name:
            return schema["function"]
    pytest.fail(f"'{name}' is in TOOL_FUNCTIONS but has no schema in TOOL_SCHEMAS. Add it in src/tools/__init__.py.")


def _properties(name: str) -> dict:
    return (_schema(name).get("parameters") or {}).get("properties", {})


def _spec_purposes() -> dict:
    """Read docs/03_tool_spec.md and return {tool name: Purpose line}."""
    purposes = {}
    for block in re.split(r"^## Tool: ", SPEC_PATH.read_text(encoding="utf-8"), flags=re.M)[1:]:
        match = re.search(r"^- Purpose: (.+)$", block, flags=re.M)
        if match:
            purposes[block.splitlines()[0].strip(" `")] = " ".join(match.group(1).split())
    return purposes


# ---- Registry ----
def test_registry_consistent():
    assert all(isinstance(s, dict) for s in TOOL_SCHEMAS), \
        "TOOL_SCHEMAS contains something that is not a schema dict (is a <NAME>_SCHEMA still None?)."
    names = [s["function"]["name"] for s in TOOL_SCHEMAS]
    assert len(names) == len(set(names)), f"Two schemas share a name: {names}"
    assert set(names) == set(TOOL_FUNCTIONS), \
        f"Schema names {sorted(names)} and TOOL_FUNCTIONS keys {sorted(TOOL_FUNCTIONS)} must be the same set."


def test_team_has_four_new_tools():
    new = set(TOOL_FUNCTIONS) - GIVEN_TOOLS
    assert len(new) >= MIN_NEW_TOOLS, \
        f"You have {len(new)} new tool(s). The assignment needs at least {MIN_NEW_TOOLS} (calculate does not count)."


# ---- What the LLM sees ----
@tool
def test_name_matches_function(name):
    assert TOOL_FUNCTIONS[name].__name__ == name, \
        f"TOOL_FUNCTIONS['{name}'] points to a function called '{TOOL_FUNCTIONS[name].__name__}'. Use the same name."


@tool
def test_description_is_clear(name):
    description = _schema(name).get("description", "")
    assert len(description.split()) >= 4, \
        f"'{name}' description is too short for the LLM to know when to call it: {description!r}"


@tool
def test_description_matches_spec(name):
    purposes = _spec_purposes()
    assert name in purposes, f"'{name}' has no '## Tool: {name}' section with a Purpose line in docs/03_tool_spec.md."
    assert " ".join(_schema(name)["description"].split()) == purposes[name], \
        f"'{name}': the schema description and the Purpose line in the spec must be the same sentence."


@tool
def test_every_parameter_is_described(name):
    assert (_schema(name).get("parameters") or {}).get("type") == "object", \
        f"'{name}' needs \"parameters\": {{\"type\": \"object\", \"properties\": {{...}}}} (empty properties if it takes none)."
    for param, spec in _properties(name).items():
        assert spec.get("type"), f"'{name}': parameter '{param}' has no \"type\"."
        assert spec.get("description"), f"'{name}': parameter '{param}' has no \"description\"."


# ---- What actually runs ----
@tool
def test_function_has_docstring(name):
    assert inspect.getdoc(TOOL_FUNCTIONS[name]), f"'{name}' has no docstring."


@tool
def test_parameters_match_function(name):
    in_function = set(inspect.signature(TOOL_FUNCTIONS[name]).parameters)
    in_schema = set(_properties(name))
    assert in_schema == in_function, \
        f"'{name}': the schema has parameters {sorted(in_schema)} but the function takes {sorted(in_function)}."


@tool
def test_required_matches_defaults(name):
    parameters = inspect.signature(TOOL_FUNCTIONS[name]).parameters.values()
    no_default = {p.name for p in parameters if p.default is inspect.Parameter.empty}
    required = set((_schema(name).get("parameters") or {}).get("required", []))
    assert required == no_default, \
        f"'{name}': \"required\" is {sorted(required)} but the parameters with no default value are {sorted(no_default)}."


@tool
def test_bad_input_returns_dict(name):
    junk = {param: JUNK.get(spec.get("type")) for param, spec in _properties(name).items()}
    try:
        result = TOOL_FUNCTIONS[name](**junk)
    except Exception as exc:
        pytest.fail(f"'{name}' raised {type(exc).__name__} for {junk}. Tools must return {{\"error\": \"...\"}}, never raise. "
                    "(If test_parameters_match_function also fails, fix that one first.)")
    assert isinstance(result, dict), f"'{name}' returned {type(result).__name__} for {junk}. Tools must return a dict."
    json.dumps(result)  # the agent sends the result to the LLM as JSON
